### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nikhilsaraf** [uinb/galois#76]
Hi, I’m interested in using your matching engine and was wondering if you could help me with the following?

1. Is there any API documentation?
2. can I run this fully in memory?
3. What is the latency to add an order / match on the orderbook?

Thank you for the help!

**Comment by cyberaurora** [comment]
Thx for your attention! But we have to apologize because we are preparing the Fusotao Network launch so we don't have too much to maintain the docs. I can just make very brief introduction here. That is the answer of your 1st question, sorry again.

For the 2nd question: yes, but you need a mysql to receive the matching result.
And the last question, you can refer the benchmarking: 100,000+CMD/s in aws z1d server.

1. If you are willing to use `Galois` to serve the Quant system, that is simple, just follow the README so you can use it. We'll introduce the command details in the future.
2. If you would like to run an exchange service by `Galois`, that is a little more complicated. There are 2 ways to do the business: with `--feature fusotao` and without it. Both of them need a broker system which is the order and user manager.

**Comment by cyberaurora** [comment]
you may want to join our [discord](https://discord.gg/DFHf2pMS) here.

**Comment by nikhilsaraf** [comment]
@cyberaurora I missed your message with the discord link and it seems to have expired, can you please post a new link?

**Comment by cyberaurora** [comment]
here [fusotao discord](https://discord.gg/ANPRvuebZV)
